/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 erlf1-ktx2.glb --transform --compress --ktx2 
Files: erlf1-ktx2.glb [7.06MB] > /Users/alirizvi/Documents/Projects/ERLF_Final/ERLF/public/erlf1-ktx2-transformed.glb [6.18MB] (12%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/erlf1-ktx2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.obj1.geometry} material={materials['Basic Concrete']} />
    </group>
  )
}

useGLTF.preload('/erlf1-ktx2-transformed.glb')
