/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model_resized.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model_resized.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.obj1.geometry} material={materials['Basic Concrete']} />
    </group>
  )
}

useGLTF.preload('/model_resized.glb')
