/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 new_erfl-2-opt.glb --transform --compress --ktx2 
Files: new_erfl-2-opt.glb [7.06MB] > /Users/alirizvi/Documents/Projects/ERLF_Final/ERLF/public/new_erfl-2-opt-transformed.glb [6.17MB] (13%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/new_erfl-2-opt-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.obj11.geometry} material={materials['Basic Concrete']} />
    </group>
  )
}

useGLTF.preload('/new_erfl-2-opt-transformed.glb')
